### ISSUE TITLE
pip install fails (error: implicit declaration of function 'H5close' is invalid in C99)

### ISSUE THREAD

**Issue by nlaws-camus** [NREL/PyDSS#109]
I am on a mac, os 12.2.1, M1 Pro and both `pip3 install dsspy` and cloning with `pip install -e PyDSS` give the same error (I tried Python 3.9 and 3.10):
```shell
% pip3 install dsspy     
Collecting dsspy
  Using cached dsspy-2.2.3-py3-none-any.whl (252 kB)
Collecting scipy
  Using cached scipy-1.9.2-cp310-cp310-macosx_12_0_arm64.whl (28.5 MB)
Collecting terminaltables
  Using cached terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
Collecting pymongo
  Downloading pymongo-4.2.0-cp310-cp310-macosx_10_15_universal2.whl (404 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.2/404.2 kB 1.4 MB/s eta 0:00:00
Collecting OpenDSSDirect.py>=0.6.0
  Using cached OpenDSSDirect.py-0.7.0-py3-none-any.whl (70 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting bokeh
  Using cached bokeh-2.4.3-py3-none-any.whl (18.5 MB)
Collecting networkx
  Using cached networkx-2.8.7-py3-none-any.whl (2.0 MB)
Collecting aiohttp-swagger3==0.4.3
  Using cached aiohttp_swagger3-0.4.3-py3-none-any.whl (1.7 MB)
Collecting tables
  Using cached tables-3.7.0.tar.gz (8.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      /var/folders/lp/z4rnw6755rb4383yr_t2bbbr0000gp/T/H5closekqkx73ks.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          H5close();
          ^
      1 error generated.
      cpuinfo failed, assuming no CPU features: No module named 'cpuinfo'
      * Using Python 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)]
      * USE_PKGCONFIG: True
      .. ERROR:: Could not find a local HDF5 installation.
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by nlaws-camus** [comment]
maybe an M1 issue. I just tried on a similar mac with intel chip and `pip install dsspy` worked with Python 3.9

**Comment by daniel-thom** [comment]
@nlaws-camus Perhaps you saw this issue: https://github.com/PyTables/PyTables/issues/832. Do workarounds listed their solve your issue?

**Comment by nlaws-camus** [comment]
Thanks @daniel-thom ! Yes the following worked:
```sh
brew install hdf5 c-blosc lzo bzip2
```
followed by
```sh
HDF5_DIR=/opt/homebrew/opt/hdf5 BLOSC_DIR=/opt/homebrew/opt/c-blosc LZO_DIR=/opt/homebrew/opt/lzo BZIP2_DIR=/opt/homebrew/opt/bzip2 pip install -e PyDSS
```

**Comment by padraic-padraic** [comment]
As a note, this is still an issue, especially with Python 3.11. Doing `export HDF5_DIR=/opt/homebrew/opt/hdf5` is sufficient for me to compile with Python 3.10, but I get an entirely different error when trying under 3.11 and pip `23.0.1`

Firstly, I again need to explicitly set the blosc, lzo and bzip2 locations as mentioned above, just setting HDF5 is insufficient. I then get the following error:
```
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --install-option is deprecated because it forces pip to use the 'setup.py install' command which is itself deprecated. pip 23.1 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11358
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting tables==3.8.0
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [244 lines of output]
      DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
      Collecting setuptools>=42.0
        Using cached setuptools-67.3.2.tar.gz (2.5 MB)
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting wheel
        Using cached wheel-0.38.4.tar.gz (67 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting oldest-supported-numpy
        Using cached oldest-supported-numpy-2022.11.19.tar.gz (4.9 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting packaging
        Using cached packaging-23.0.tar.gz (126 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting py-cpuinfo
        Using cached py-cpuinfo-9.0.0.tar.gz (104 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting Cython>=0.29.21
        Using cached Cython-0.29.33.tar.gz (2.1 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blosc2~=2.0.0
        Using cached blosc2-2.0.0.tar.gz (3.0 MB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [185 lines of output]
            DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
            Collecting setuptools
              Using cached setuptools-67.3.2.tar.gz (2.5 MB)
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting scikit-build
              Using cached scikit-build-0.16.7.tar.gz (274 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting cython
              Using cached Cython-0.29.33.tar.gz (2.1 MB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting cmake
              Using cached cmake-3.25.2.tar.gz (33 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting ninja
              Downloading ninja-1.11.1.tar.gz (27 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting oldest-supported-numpy
              Using cached oldest-supported-numpy-2022.11.19.tar.gz (4.9 kB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting distro
              Using cached distro-1.8.0.tar.gz (59 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting packaging
              Using cached packaging-23.0.tar.gz (126 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting wheel>=0.32.0
              Using cached wheel-0.38.4.tar.gz (67 kB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting numpy==1.23.2
              Using cached numpy-1.23.2.tar.gz (10.7 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'error'
              error: subprocess-exited-with-error

              × Getting requirements to build wheel did not run successfully.
              │ exit code: 1
              ╰─> [95 lines of output]
                  <string>:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
                  Running from numpy source directory.
                  <string>:86: DeprecationWarning:

                    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
                    of the deprecation of `distutils` itself. It will be removed for
                    Python >= 3.12. For older Python versions it will remain present.
                    It is recommended to use `setuptools < 60.0` for those Python versions.
                    For more details, see:
                      https://numpy.org/devdocs/reference/distutils_status_migration.html


                  running egg_info
                  running build_src
                  INFO: build_src
                  creating numpy.egg-info
                  writing numpy.egg-info/PKG-INFO
                  writing dependency_links to numpy.egg-info/dependency_links.txt
                  writing entry points to numpy.egg-info/entry_points.txt
                  writing top-level names to numpy.egg-info/top_level.txt
                  writing manifest file 'numpy.egg-info/SOURCES.txt'
                  /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py:643: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
                  Please extend command classes from setuptools instead of distutils.
                    warnings.warn(
                  INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
                  Traceback (most recent call last):
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                      main()
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                      json_out['return_val'] = hook(**hook_input['kwargs'])
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                      return hook(config_settings)
                             ^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
                      return self._get_build_requires(config_settings, requirements=['wheel'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
                      self.run_setup()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
                      self).run_setup(setup_script=setup_script)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
                      exec(code, locals())
                    File "<string>", line 493, in <module>
                    File "<string>", line 485, in setup_package
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
                      return distutils.core.setup(**attrs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
                      return run_commands(dist)
                             ^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                      dist.run_commands()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                      self.run_command(cmd)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
                      super().run_command(command)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                      cmd_obj.run()
                    File "/private/var/folders/ps/dwlk96k15fl7_csnxt2q57dc0000gn/T/pip-install-se5mtmkp/numpy_e6c0a52c426d425ea06850a820c627f6/numpy/distutils/command/egg_info.py", line 25, in run
                      _egg_info.run(self)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 308, in run
                      self.find_sources()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
                      mm.run()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 560, in run
                      self.add_defaults()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
                      sdist.add_defaults(self)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
                      self._add_defaults_build_sub_commands()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
                      self.filelist.extend(chain.from_iterable(files))
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 503, in extend
                      self.files.extend(filter(self._safe_path, paths))
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
                      files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
                      cmds = (self.get_finalized_command(c) for c in missing_cmds)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
                      cmd_obj.ensure_finalized()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
                      self.finalize_options()
                    File "/private/var/folders/ps/dwlk96k15fl7_csnxt2q57dc0000gn/T/pip-install-se5mtmkp/numpy_e6c0a52c426d425ea06850a820c627f6/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
                      v = getattr(c, a)
                          ^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
                      return _build_ext.build_ext.__getattr__(self, name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
                      raise AttributeError(attr)
                  AttributeError: fcompiler. Did you mean: 'compiler'?
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: subprocess-exited-with-error

            × Getting requirements to build wheel did not run successfully.
            │ exit code: 1
            ╰─> See above for output.

            note: This error originates from a subprocess, and is likely not a problem with pip.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

Though it's possible this is a setuptools issue, as this is the only other recent hit https://github.com/pypa/setuptools/issues/3549
